
// Objective-C API for talking to the following Go packages
//
//	github.com/FISCO-BCOS/go-sdk/mobile/iOS
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Fiscobcosios_FRAMEWORK_H__
#define __Fiscobcosios_FRAMEWORK_H__

#include "Fiscobcosios.objc.h"
#include "Universe.objc.h"

#endif
