// Objective-C API for talking to github.com/FISCO-BCOS/go-sdk/mobile/iOS Go package.
//   gobind -lang=objc github.com/FISCO-BCOS/go-sdk/mobile/iOS
//
// File is generated by gobind. Do not edit.

#ifndef __Fiscobcosios_H__
#define __Fiscobcosios_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FiscobcosiosBuildSDKResult;
@class FiscobcosiosCallResult;
@class FiscobcosiosContractParams;
@class FiscobcosiosDeployContractResult;
@class FiscobcosiosEventLog;
@class FiscobcosiosFullTransaction;
@class FiscobcosiosRPCResult;
@class FiscobcosiosRPCTransactionResult;
@class FiscobcosiosSendTransactionReceipt;
@class FiscobcosiosTransactResult;
@class FiscobcosiosTransaction;
@class FiscobcosiosTxReceipt;

@interface FiscobcosiosBuildSDKResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long errorId;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosCallResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull result;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosContractParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull valueType;
// skipped field ContractParams.Value with unsupported type: interface{}

@end

@interface FiscobcosiosDeployContractResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull errorInfo;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) FiscobcosiosTransaction* _Nullable transaction;
@end

@interface FiscobcosiosEventLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
// skipped field EventLog.Topics with unsupported type: []string

@end

@interface FiscobcosiosFullTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull gas;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull nonce;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface FiscobcosiosRPCResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull queryResult;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosRPCTransactionResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field RPCTransactionResult.Transaction with unsupported type: github.com/FISCO-BCOS/go-sdk/mobile/iOS.FullTransaction

@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosSendTransactionReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosTransactResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) FiscobcosiosTransaction* _Nullable transaction;
@property (nonatomic) FiscobcosiosTxReceipt* _Nullable receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscobcosiosTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) double size;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface FiscobcosiosTxReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull transactionHash;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull gasUsed;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull root;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull output;
// skipped field TxReceipt.Logs with unsupported type: []github.com/FISCO-BCOS/go-sdk/mobile/iOS.EventLog

@property (nonatomic) NSString* _Nonnull logsBloom;
@end

/**
 * Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
FOUNDATION_EXPORT NSString* _Nonnull FiscobcosiosBuildSDK(NSString* _Nullable basePath);

/**
 * Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
FOUNDATION_EXPORT NSString* _Nonnull FiscobcosiosBuildSDKWithParam(NSString* _Nullable basePath, NSString* _Nullable groupId, NSString* _Nullable ipPort, NSString* _Nullable keyfile);

/**
 * Call contract
 */
FOUNDATION_EXPORT FiscobcosiosCallResult* _Nullable FiscobcosiosCall(NSString* _Nullable abiContract, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

/**
 * Deploy contract
 */
FOUNDATION_EXPORT FiscobcosiosDeployContractResult* _Nullable FiscobcosiosDeployContract(NSString* _Nullable abiContract, NSString* _Nullable binContract, NSString* _Nullable params);

/**
 * Get client version
 */
FOUNDATION_EXPORT FiscobcosiosRPCResult* _Nullable FiscobcosiosGetClientVersion(void);

/**
 * Get transaction by tx hash
 */
FOUNDATION_EXPORT FiscobcosiosRPCTransactionResult* _Nullable FiscobcosiosGetTransactionByHash(NSString* _Nullable txHash);

/**
 * Get transaction receipt by tx hash
 */
FOUNDATION_EXPORT FiscobcosiosRPCResult* _Nullable FiscobcosiosGetTransactionReceipt(NSString* _Nullable txHash);

/**
 * Send transaction to call function of contract
 */
FOUNDATION_EXPORT FiscobcosiosTransactResult* _Nullable FiscobcosiosSendTransaction(NSString* _Nullable abiContract, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

// skipped function StringToInterface with unsupported parameter or return types


// skipped function TestTransfer with unsupported parameter or return types


#endif
