// Objective-C API for talking to github.com/FISCO-BCOS/go-sdk/fiscoBcosMobile Go package.
//   gobind -lang=objc github.com/FISCO-BCOS/go-sdk/fiscoBcosMobile
//
// File is generated by gobind. Do not edit.

#ifndef __FiscoBcosMobile_H__
#define __FiscoBcosMobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FiscoBcosMobileBuildSDKResult;
@class FiscoBcosMobileCallResult;
@class FiscoBcosMobileContractParams;
@class FiscoBcosMobileDeployContractResult;
@class FiscoBcosMobileEventLog;
@class FiscoBcosMobileFullTransaction;
@class FiscoBcosMobileRPCResult;
@class FiscoBcosMobileRPCTransactionResult;
@class FiscoBcosMobileSendTransactionReceipt;
@class FiscoBcosMobileTransactResult;
@class FiscoBcosMobileTransaction;
@class FiscoBcosMobileTxReceipt;

@interface FiscoBcosMobileBuildSDKResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long errorId;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileCallResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull result;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileContractParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull valueType;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface FiscoBcosMobileDeployContractResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull errorInfo;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) FiscoBcosMobileTransaction* _Nullable transaction;
@end

@interface FiscoBcosMobileEventLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
// skipped field EventLog.Topics with unsupported type: []string

@end

@interface FiscoBcosMobileFullTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull gas;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull nonce;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface FiscoBcosMobileRPCResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull queryResult;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileRPCTransactionResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field RPCTransactionResult.Transaction with unsupported type: github.com/FISCO-BCOS/go-sdk/fiscoBcosMobile.FullTransaction

@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileSendTransactionReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileTransactResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) FiscoBcosMobileTransaction* _Nullable transaction;
@property (nonatomic) FiscoBcosMobileTxReceipt* _Nullable receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface FiscoBcosMobileTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) double size;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface FiscoBcosMobileTxReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull transactionHash;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull gasUsed;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull root;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull output;
// skipped field TxReceipt.Logs with unsupported type: []github.com/FISCO-BCOS/go-sdk/fiscoBcosMobile.EventLog

@property (nonatomic) NSString* _Nonnull logsBloom;
@end

/**
 * Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
FOUNDATION_EXPORT NSString* _Nonnull FiscoBcosMobileBuildSDK(NSString* _Nullable basePath);

/**
 * Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
FOUNDATION_EXPORT NSString* _Nonnull FiscoBcosMobileBuildSDKWithParam(NSString* _Nullable basePath, NSString* _Nullable groupId, NSString* _Nullable ipPort, NSString* _Nullable keyfile);

/**
 * Call contract
 */
FOUNDATION_EXPORT FiscoBcosMobileCallResult* _Nullable FiscoBcosMobileCall(NSString* _Nullable abiContract, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

/**
 * Deploy contract
 */
FOUNDATION_EXPORT FiscoBcosMobileDeployContractResult* _Nullable FiscoBcosMobileDeployContract(NSString* _Nullable abiContract, NSString* _Nullable binContract, NSString* _Nullable params);

/**
 * Get client version
 */
FOUNDATION_EXPORT FiscoBcosMobileRPCResult* _Nullable FiscoBcosMobileGetClientVersion(void);

FOUNDATION_EXPORT FiscoBcosMobileRPCTransactionResult* _Nullable FiscoBcosMobileGetTransactionByHash(NSString* _Nullable txHash);

FOUNDATION_EXPORT FiscoBcosMobileRPCResult* _Nullable FiscoBcosMobileGetTransactionReceipt(NSString* _Nullable txHash);

/**
 * Send transaction to call function of contract
 */
FOUNDATION_EXPORT FiscoBcosMobileTransactResult* _Nullable FiscoBcosMobileSendTransaction(NSString* _Nullable abiContract, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

// skipped function StringToInterface with unsupported parameter or return types


// skipped function TestTransfer with unsupported parameter or return types


#endif
