
// Objective-C API for talking to the following Go packages
//
//	github.com/FISCO-BCOS/go-sdk/fiscoBcosMobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FiscoBcosMobile_FRAMEWORK_H__
#define __FiscoBcosMobile_FRAMEWORK_H__

#include "FiscoBcosMobile.objc.h"
#include "Universe.objc.h"

#endif
