// Objective-C API for talking to github.com/FISCO-BCOS/go-sdk/mobile/ios Go package.
//   gobind -lang=objc github.com/FISCO-BCOS/go-sdk/mobile/ios
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileBcosSDK;
@class MobileBuildSDKResult;
@class MobileCallResult;
@class MobileContractParams;
@class MobileDeployContractResult;
@class MobileEventLog;
@class MobileFullTransaction;
@class MobileRPCResult;
@class MobileRPCTransactionResult;
@class MobileSendTransactionReceipt;
@class MobileTransactResult;
@class MobileTransaction;
@class MobileTxReceipt;
@protocol MobilePostCallback;
@class MobilePostCallback;

@protocol MobilePostCallback <NSObject>
- (NSString* _Nonnull)sendResult:(NSString* _Nullable)rpcRequest;
@end

@interface MobileBcosSDK : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) id<MobilePostCallback> _Nullable callback;
/**
 * BuildSDK
Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
- (MobileBuildSDKResult* _Nullable)buildSDK:(NSString* _Nullable)configString;
/**
 * BuildSDKWithParam
Connect to the proxy or FISCO BCOS node.
Please make sure ca.crt, sdk.crt, sdk.key under path certPath.
Please provider full keyFile path
 */
- (MobileBuildSDKResult* _Nullable)buildSDKWithParam:(NSString* _Nullable)certPath keyFile:(NSString* _Nullable)keyFile groupId:(long)groupId ipPort:(NSString* _Nullable)ipPort isHttp:(BOOL)isHttp chainId:(int64_t)chainId isSMCrypto:(BOOL)isSMCrypto;
/**
 * Call contract
 */
- (MobileCallResult* _Nullable)call:(NSString* _Nullable)abiContract address:(NSString* _Nullable)address method:(NSString* _Nullable)method params:(NSString* _Nullable)params;
/**
 * DeployContract
Deploy contract
 */
- (MobileDeployContractResult* _Nullable)deployContract:(NSString* _Nullable)contractAbi contractBin:(NSString* _Nullable)contractBin params:(NSString* _Nullable)params;
/**
 * GetBlockNumber
Return block number
 */
- (MobileRPCResult* _Nullable)getBlockNumber;
/**
 * RPC calls
GetClientVersion
 */
- (MobileRPCResult* _Nullable)getClientVersion;
/**
 * GetTransactionByHash
Get transaction by tx hash
 */
- (MobileRPCTransactionResult* _Nullable)getTransactionByHash:(NSString* _Nullable)txHash;
/**
 * GetTransactionReceipt
Get transaction receipt by tx hash
 */
- (MobileRPCResult* _Nullable)getTransactionReceipt:(NSString* _Nullable)txHash;
/**
 * SendTransaction
Send transaction to call function of contract
 */
- (MobileTransactResult* _Nullable)sendTransaction:(NSString* _Nullable)contractAbi address:(NSString* _Nullable)address method:(NSString* _Nullable)method params:(NSString* _Nullable)params;
@end

@interface MobileBuildSDKResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL isSuccess;
@property (nonatomic) NSString* _Nonnull information;
@end

@interface MobileCallResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull result;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileContractParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull valueType;
// skipped field ContractParams.Value with unsupported type: interface{}

@end

@interface MobileDeployContractResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull errorInfo;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) MobileTransaction* _Nullable transaction;
@end

@interface MobileEventLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
// skipped field EventLog.Topics with unsupported type: []string

@end

@interface MobileFullTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull gas;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull nonce;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface MobileRPCResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull queryResult;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileRPCTransactionResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field RPCTransactionResult.Transaction with unsupported type: github.com/FISCO-BCOS/go-sdk/mobile/ios.FullTransaction

@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileSendTransactionReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileTransactResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) MobileTransaction* _Nullable transaction;
@property (nonatomic) MobileTxReceipt* _Nullable receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) double size;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface MobileTxReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull transactionHash;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull gasUsed;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull root;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull output;
// skipped field TxReceipt.Logs with unsupported type: []github.com/FISCO-BCOS/go-sdk/mobile/ios.EventLog

@property (nonatomic) NSString* _Nonnull logsBloom;
@end

@class MobilePostCallback;

@interface MobilePostCallback : NSObject <goSeqRefInterface, MobilePostCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)sendResult:(NSString* _Nullable)rpcRequest;
@end

#endif
