// Objective-C API for talking to github.com/FISCO-BCOS/go-sdk/mobile/ios Go package.
//   gobind -lang=objc github.com/FISCO-BCOS/go-sdk/mobile/ios
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileBuildSDKResult;
@class MobileCallResult;
@class MobileContractParams;
@class MobileDeployContractResult;
@class MobileEventLog;
@class MobileFullTransaction;
@class MobileRPCResult;
@class MobileRPCTransactionResult;
@class MobileSendTransactionReceipt;
@class MobileTransactResult;
@class MobileTransaction;
@class MobileTxReceipt;

@interface MobileBuildSDKResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL isSuccess;
@property (nonatomic) NSString* _Nonnull information;
@end

@interface MobileCallResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull result;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileContractParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull valueType;
// skipped field ContractParams.Value with unsupported type: interface{}

@end

@interface MobileDeployContractResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull errorInfo;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) MobileTransaction* _Nullable transaction;
@end

@interface MobileEventLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
// skipped field EventLog.Topics with unsupported type: []string

@end

@interface MobileFullTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull gas;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull nonce;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface MobileRPCResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull queryResult;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileRPCTransactionResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field RPCTransactionResult.Transaction with unsupported type: github.com/FISCO-BCOS/go-sdk/mobile/ios.FullTransaction

@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileSendTransactionReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileTransactResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) MobileTransaction* _Nullable transaction;
@property (nonatomic) MobileTxReceipt* _Nullable receipt;
@property (nonatomic) NSString* _Nonnull errorInfo;
@end

@interface MobileTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) double size;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface MobileTxReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull transactionHash;
@property (nonatomic) NSString* _Nonnull transactionIndex;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull gasUsed;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull root;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull input;
@property (nonatomic) NSString* _Nonnull output;
// skipped field TxReceipt.Logs with unsupported type: []github.com/FISCO-BCOS/go-sdk/mobile/ios.EventLog

@property (nonatomic) NSString* _Nonnull logsBloom;
@end

/**
 * BuildSDK
Build sdk.
Connect to the proxy or FISCO BCOS node.
 */
FOUNDATION_EXPORT MobileBuildSDKResult* _Nullable MobileBuildSDK(NSString* _Nullable configString);

/**
 * BuildSDKWithParam
Connect to the proxy or FISCO BCOS node.
Please make sure ca.crt, sdk.crt, sdk.key under path certPath.
Please provider full keyFile path
 */
FOUNDATION_EXPORT MobileBuildSDKResult* _Nullable MobileBuildSDKWithParam(NSString* _Nullable certPath, NSString* _Nullable keyFile, long groupId, NSString* _Nullable ipPort, BOOL isHttp, int64_t chainId, BOOL isSMCrypto);

/**
 * Call contract
 */
FOUNDATION_EXPORT MobileCallResult* _Nullable MobileCall(NSString* _Nullable abiContract, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

/**
 * DeployContract
Deploy contract
 */
FOUNDATION_EXPORT MobileDeployContractResult* _Nullable MobileDeployContract(NSString* _Nullable abiContract, NSString* _Nullable binContract, NSString* _Nullable params);

/**
 * GetBlockNumber
Return block number
 */
FOUNDATION_EXPORT MobileRPCResult* _Nullable MobileGetBlockNumber(void);

/**
 * RPC calls
GetClientVersion
 */
FOUNDATION_EXPORT MobileRPCResult* _Nullable MobileGetClientVersion(void);

/**
 * GetTransactionByHash
Get transaction by tx hash
 */
FOUNDATION_EXPORT MobileRPCTransactionResult* _Nullable MobileGetTransactionByHash(NSString* _Nullable txHash);

/**
 * GetTransactionReceipt
Get transaction receipt by tx hash
 */
FOUNDATION_EXPORT MobileRPCResult* _Nullable MobileGetTransactionReceipt(NSString* _Nullable txHash);

/**
 * SendTransaction
Send transaction to call function of contract
 */
FOUNDATION_EXPORT MobileTransactResult* _Nullable MobileSendTransaction(NSString* _Nullable contractAbi, NSString* _Nullable address, NSString* _Nullable method, NSString* _Nullable params);

// skipped function StringToInterface with unsupported parameter or return types


#endif
